# Generated by Django 2.1.7 on 2019-03-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_bookcheckouthistory_date_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcheckouthistory',
            name='book_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bookcheckouthistory',
            name='book_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='bookcheckouthistory',
            name='days_rented',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
