# Generated by Django 2.1.7 on 2019-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190315_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcheckouthistory',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
