# Generated by Django 2.1.7 on 2019-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190315_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercheckouthistory',
            name='latest_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
