# Generated by Django 2.1.7 on 2019-03-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190315_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateReturnedCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_out_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.CustomerCheckoutHistory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bookcheckouthistory',
            name='date_return_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.DateReturnedCost'),
        ),
    ]
