# Generated by Django 2.1.7 on 2019-03-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def create_book_category_update_books(apps, schema_editor):
        BookCategory = apps.get_model('bookstore', 'BookCategory')
        regular_type = BookCategory.objects.create(code='Reg', name='Regular', charge_per_day=1.5)
        fiction_type = BookCategory.objects.create(code='Fic', name='Fiction', charge_per_day=3.0)
        novel_type = BookCategory.objects.create(code='Nov', name='Novel', charge_per_day=1.5)

        Book = apps.get_model('bookstore', 'Book')
        regular_books_code = ['001', '002']
        fiction_books_code = ['004']
        novel_books_code = ['005']

        # Update book categories for each book
        books = Book.objects.all()
        for book in books:
            if book.code in regular_books_code:
                book.book_category = regular_type
            elif book.code in fiction_books_code:
                book.book_category = fiction_type
            elif book.code in novel_books_code:
                book.book_category = novel_type
            else:
                book.book_category = regular_type
            book.save()

    dependencies = [
        ('bookstore', '0005_auto_20190316_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('charge_per_day', models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.BookCategory'),
        ),
        migrations.RunPython(create_book_category_update_books, reverse_code=migrations.RunPython.noop),
    ]
