# Generated by Django 2.1.7 on 2019-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    def update_rates(apps, schema_editor):
        BookCategory = apps.get_model('bookstore', 'BookCategory')
        # Update regular type
        regular_type = BookCategory.objects.get(code='Reg')
        regular_type.starting_charge = 1.0
        regular_type.starting_charge_day_limit = 2
        regular_type.minimum_charge = 2.0
        regular_type.minimum_charge_day_limit = 2
        regular_type.save()

        # Update novel type
        novel_type = BookCategory.objects.get(code='Nov')
        novel_type.minimum_charge = 4.5
        novel_type.minimum_charge_day_limit = 3.0
        novel_type.save()

    dependencies = [
        ('bookstore', '0006_auto_20190317_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='minimum_charge_day_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='starting_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='starting_charge_day_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(update_rates, reverse_code=migrations.RunPython.noop)
    ]